name: vis
channels:
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=2_kmp_llvm
  - ca-certificates=2023.7.22=hbcca054_0
  - glfw=3.3.8=hd590300_1
  - ld_impl_linux-64=2.38=h1181459_1
  - libffi=3.4.4=h6a678d5_0
  - libgcc-ng=13.2.0=h807b86a_2
  - libstdcxx-ng=13.2.0=h7e041cc_2
  - libxcb=1.15=h0b41bf4_0
  - llvm-openmp=14.0.6=h9e868ea_0
  - ncurses=6.4=h6a678d5_0
  - openssl=3.1.3=hd590300_0
  - pip=23.2.1=py38h06a4308_0
  - pthread-stubs=0.4=h36c2ea0_1001
  - pyglfw=2.6.2=py38h578d9bd_0
  - python=3.8.18=h955ad1f_0
  - python_abi=3.8=2_cp38
  - readline=8.2=h5eee18b_0
  - setuptools=68.0.0=py38h06a4308_0
  - sqlite=3.41.2=h5eee18b_0
  - tk=8.6.12=h1ccaba5_0
  - wheel=0.38.4=py38h06a4308_0
  - xorg-fixesproto=5.0=h7f98852_1002
  - xorg-kbproto=1.0.7=h7f98852_1002
  - xorg-libx11=1.8.6=h8ee46fc_0
  - xorg-libxau=1.0.11=hd590300_0
  - xorg-libxcursor=1.2.0=h0b41bf4_1
  - xorg-libxdmcp=1.1.3=h7f98852_0
  - xorg-libxext=1.3.4=h0b41bf4_2
  - xorg-libxfixes=5.0.3=h7f98852_1004
  - xorg-libxinerama=1.1.5=h27087fc_0
  - xorg-libxrandr=1.5.2=h7f98852_1
  - xorg-libxrender=0.9.11=hd590300_0
  - xorg-randrproto=1.5.0=h7f98852_1001
  - xorg-renderproto=0.11.1=h7f98852_1002
  - xorg-xextproto=7.3.0=h0b41bf4_1003
  - xorg-xproto=7.0.31=h7f98852_1007
  - xz=5.4.2=h5eee18b_0
  - zlib=1.2.13=h5eee18b_0
  - pip:
      - absl-py==2.0.0
      - contourpy==1.1.1
      - cycler==0.11.0
      - fonttools==4.42.1
      - importlib-resources==6.1.0
      - kiwisolver==1.4.5
      - matplotlib==3.7.3
      - multipledispatch==1.0.0
      - numpy==1.24.4
      - opencv-python==4.8.0.76
      - packaging==23.1
      - pillow==10.0.1
      - plyfile==1.0.1
      - pyopengl==3.1.7
      - pyparsing==3.1.1
      - pyrr==0.10.3
      - python-dateutil==2.8.2
      - six==1.16.0
      - zipp==3.17.0
